version: "3"

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rolebit
    container_name: rolebit_container
    ports:
      - "3000:3001"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ".env.development"